#!/bin/sh

set -e

WORK_DIR=$(pwd)

echo "Executing golang linter"
cd "$WORK_DIR/api" || exit 1
if [ "$(gofmt -d . | tee /dev/tty | wc -l)" -gt 0 ]; then
    exit 1
fi

echo "Executing golang tests..."
cd "$WORK_DIR/api" && go test ./...

echo "Executing frontend linter..."
cd "$WORK_DIR/web" && npm run lint && npm run test -- --watchAll=false
