before:
  hooks:
    - cp ../README.md ./README.md
    - cp ../LICENSE ./LICENSE
    - go get github.com/swaggo/swag/cmd/swag
    - go get github.com/GeertJohan/go.rice/rice
    - go mod download
    - swag init
    - rice embed-go

builds:
  - goos:
      - linux
    goarch:
      - amd64

archives:
  - files:
      - config.example.yaml
      - README.md
      - LICENSE

checksum:
  algorithm: sha512

release:
  github:
    owner: sipgate
    name: gnt-cc
  draft: true
  prerelease: auto

changelog:
  sort: asc

nfpms:
  - package_name: gnt-cc
    vendor: sipgate
    homepage: https://github.com/sipgate/gnt-cc
    description: API + web frontend for multiple Ganeti virtualisation clusters
    license: Apache 2.0
    formats:
      - deb
    contents:
      - src: config.example.yaml
        dst: /etc/gnt-cc/config.example.yaml
